### ISSUE TITLE
The new `ocaml-freestanding` layout does not handle frame-pointers/nnp-checkers

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-solo5#106]
This feature from the OCaml distribution expects that the toolchain used to compile OCaml must be `gcc` or `clang` and it recognizes it by the name of the toolchain. In our case, our toolchain is: `{x86_64,arm64}-solo5-none-static`. So we failed on this specific test at the `configure` time.

**Comment by hannesm** [comment]
the `no-naked-pointers` (nnp) and `naked-pointers` (np) modes are nicely supported, what is not supported is the nnpchecker (since it is only available on specific architectures).

**Comment by dinosaure** [comment]
Oh ok, so it's only `nnpchecker` and `fp`.

**Comment by hannesm** [comment]
..and that's fine for us, or isn't it? I don't understand whether we should change anything here!?

**Comment by hannesm** [comment]
closing, please reopen if there's something we should do
