### ISSUE TITLE
Add an easy way to set-up the dev environment for this package

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-solo5#119]
Right now, `dune build` or `make` will fail after a fresh clone. As `./configure` command is quite involved, it'd be nice to have a quick way to setup an environment where we could start testing.

**Comment by hannesm** [comment]
There are CI runners that test this repository. I consider that to be easy enough. If there's something concrete you have in mind, please don't hesitate to open a PR (or reopen this issue). Thanks.
