### ISSUE TITLE
Use `ocaml-ci` on this repository

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-solo5#96]

**Comment by hannesm** [comment]
I don't think OCaml-CI is feasible for this repository. It is supposed to be a "zero configuration" CI system, and in OCaml-solo5 we have some more intricate things than "dune build". I'm happy we have a GitHub action CI and cirrus CI, and will close this PR. If someone feels motivated to work on ocaml-ci for this repository, I won't stop them. But I guess it is a tough project.
